#windowrule=workspace 2 silent,class:firefox
#windowrule=workspace 3 silent,class:thunderbird
#windowrule=workspace 4 silent,class:Slack
#windowrule=workspace 9 silent,class:caprine
#windowrulev2 = workspace 10, initialTitle:^(Spotify.*)$
#windowrulev2 = workspace 9, initialClass:^(mesengeris.*)$

#$dropterm  = ^(term-dropterm)$
#windowrule = float,class:$dropterm
#windowrule = workspace special silent,class:$dropterm
#windowrule = size 75% 60%,class:$dropterm

#$console  = ^(term-console)$
#windowrule = float,class:$console
#windowrule = workspace special silent,class:$console
#windowrule = size 75% 60%,class:$console

#$namai  = ^(term-namai)$
#windowrule = float,class:$namai
#windowrule = workspace special silent,class:$namai
#windowrule = size 75% 60%,class:$namai

#$t2  = ^(term-t2)$
#windowrule = float,class:$t2
#windowrule = workspace special silent,class:$t2
#windowrule = size 75% 60%,class:$t2



# --- Apps to workspaces ---
windowrule = match:class ^(firefox)$,      workspace 2 silent
windowrule = match:class ^(thunderbird)$, workspace 3 silent
windowrule = match:class ^(Slack)$,       workspace 4 silent
windowrule = match:class ^(caprine)$,     workspace 9 silent

windowrule = match:initial_title ^(Spotify.*)$,        workspace 10
windowrule = match:initial_class ^(mesengeris.*)$,     workspace 9


# --- Special dropdown terminals ---
$dropterm = ^(term-dropterm)$
windowrule = match:class $dropterm, float on
windowrule = match:class $dropterm, workspace special silent
windowrule = match:class $dropterm, size 75% 60%

$console = ^(term-console)$
windowrule = match:class $console, float on
windowrule = match:class $console, workspace special silent
windowrule = match:class $console, size 75% 60%

$namai = ^(term-namai)$
windowrule = match:class $namai, float on
windowrule = match:class $namai, workspace special silent
windowrule = match:class $namai, size 75% 60%

$t2 = ^(term-t2)$
windowrule = match:class $t2, float on
windowrule = match:class $t2, workspace special silent
windowrule = match:class $t2, size 75% 60%

